name: Version Bump
on:
  push:
    branches:
      - version-bump

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read

  #   strategy:
  #     matrix:
  #       node-version: [12.x, 14.x, 16.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npm run build --if-present

  bump:
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
      - run: npm ci
      - run: npm run release
